# Generated by Django 3.0.4 on 2020-03-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='messageBoard',
        ),
    ]
