# Generated by Django 3.0.4 on 2020-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200317_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='usernameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=20)),
                ('ticket', models.CharField(default='WTF', max_length=100)),
            ],
        ),
    ]
