# Generated by Django 3.0.4 on 2020-03-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_usernameinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='message.usernameInfo'),
        ),
    ]
