# Generated by Django 3.0.4 on 2020-03-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20200320_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageboard',
            old_name='username',
            new_name='uUsername',
        ),
        migrations.RemoveField(
            model_name='usernameinfo',
            name='ticket',
        ),
        migrations.AddField(
            model_name='usernameinfo',
            name='tickettoken',
            field=models.CharField(default='WTF', max_length=64, null=True, unique=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='usernameinfo',
            name='passwd',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usernameinfo',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='username'),
        ),
    ]
