# Generated by Django 3.0.4 on 2020-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20200324_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernameinfo',
            name='tickettoken',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='status'),
        ),
    ]
