# Generated by Django 3.0.4 on 2020-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20200325_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads', verbose_name='image'),
        ),
    ]
