# Generated by Django 3.0.4 on 2020-03-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_messageboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='image',
        ),
    ]
